
//CONST E O IDEAL PRA MAIORIA DOS CASOS, ELA E IMUTAVEL NO SENTIDO DA REFERENCIA E NÃO DO VALOR

const courseName="Type boot"

//NUNCA USE VAR, VAR ELA DEIXA AS VARIAVEIS FORA DOS ESCOPOS, O ESCOPO E TODO O ARQUIVO TS

//LET TAMBEM TEM ESCOPO, MAS E MUTAVEL A REFERENCIA

printCourseName(courseName);
function printCourseName(name:string){
    console.log("teste",name);
}
